### ISSUE TITLE
Storybook 7 crash yarn start

### ISSUE THREAD

**Issue by ma10as** [dannyhw/expo-template-storybook#11]
Hey @dannyhw , this is an awesome project, just what I needed to get started with Storybook for my expo app.

After installing the template all the functions work fine.

When you run `yarn storybook:web` the terminal tells you that "Storybook 6.5.16 for React started" and "A new version (7.4.6) is available!"  Upgrade now: `npx storybook@latest upgrade`

After the upgrade I run `yarn start` and try to open the app on a device I get this error.
```
Android Bundling failed 627ms
Unable to resolve "@storybook/react/dist/modern/client/docs/extractArgTypes" from ".ondevice/doctools.js"
```

**Comment by dannyhw** [comment]
@ma10as this is because react native storybook is not yet compatible with version 7 the latest stable version for react native is `6.5.6`.  I would recommend not upgrading until v7 is stable for react native.

**Comment by ma10as** [comment]
Thank you very much for your answer.
I'm waiting to upgrade, I just wanted to be sure it wasn't me who did something wrong.
