### ISSUE TITLE
How is this supposed to be used?

### ISSUE THREAD

**Issue by Nautman** [dannyhw/expo-template-storybook#3]
Hi,

I have been struggling with using storybook in my React Native project. This template is the one that currently works the best. However, I am wondering how I am supposed to use the components that I develop both in my app and in my storybook?

Currently, I have set up a normal Expo app, with a subfolder where this template exists. Then I have made aliases in my app to get the components from `storybook/components`. Then, my problem becomes that there exists two copies of react in my app. One in `node_modules/react` and one in `storybook/node_modules/react`.

If you could please help guide me in the right direction of how I am supposed to use the components that I develop in a storybook in my actual app I would be very very grateful.

Thank you.

**Comment by dannyhw** [comment]
Hey :), yeah I would follow the approach in #1 like you said 👍
